export const GET_REFERENCES_TOTAL = 'GET_REFERENCES_TOTAL';
export const GET_BENEFICIARIES_TOTAL = 'GET_BENEFICIARIES_TOTAL';
export const GET_INTERVENTIONS_COUNT = 'GET_INTERVENTIONS_COUNT';
export const ERROR = 'ERROR';